### PR TITLE
[misc] Comment out list of family members (from PT-core) on Fdashboard

### PR DESCRIPTION
**Pull request by teyden**

### CODE REVIEW

**Comment by sdumitriu** [comment]
This wasn't needed, since the entire extension is disabled.

**Comment by teyden** [comment]
Yes, I disabled it, but it still displays on the family dashboard, so I commented out the line that renders the list of members as a temporary fix. Do you know why this page still gets rendered even though it has been disabled?

**Comment by marta-** [comment]
@teyden I don't know the whole context, but I would assume it's because the livetable is configured to show that field. Unfortunately the form and the table are configured independently.

**Comment by marta-** [comment]
@teyden It's because [we disable with `disable=true`](https://github.com/Gene42/phenotips-niaid/blob/master/family-dashboard/ui/src/main/resources/PhenoTips/FamilySheet.xml#L69), not with [`enable=false`](https://github.com/Gene42/phenotips-niaid/blob/5f0567392cd054331d49fa8d0c6419264209013c/family-dashboard/ui/src/main/resources/PhenoTips/FamilyRecordField_members.xml#L127).

**Comment by marta-** [comment]
@teyden nevermind, that was for sections, not for extensions... Looks like 1/ we're inconsistent in our way of marking something as disabled, and 2/ [we completely ignore the enabled/disabled status for extensions within a section on the family page](https://github.com/Gene42/phenotips-niaid/blob/master/family-dashboard/ui/src/main/resources/PhenoTips/FamilySheet.xml#L72).

**Comment by teyden** [comment]
Oh I see. It indeed looks like it's be a combination of both. I can add the check to the FamilySheet.  I'll check for 'enabled' for now since it looks like all the extensions use that parameter - but it should be changed globally eventually.

**Comment by marta-** [comment]
@teyden I'm just about to start cleaning up the familysheet for PhenoTips core and it will include this fix.

**Comment by teyden** [comment]
@marta: great, please direct me to the fix when you are complete. Thanks.

**Comment by marta-** [comment]
@teyden PR open for PhenoTips core here: https://github.com/phenotips/phenotips/pull/2143 .
The commit you'd need in is https://github.com/phenotips/phenotips/pull/2143/commits/4ce04140742e6121a87fca5538f7e17a43a6965c . If all goes well this will go into master soon and will be part of 1.3-milestone-4 to be released later this week.

**Pull request merged**
