### PR TITLE
Added column to patient data table for family id

### PR DESCRIPTION
**Pull request by Ruxuan**
@danielpgross Please review.

WebHome.xml not displayed b/c diff is too large. The difference is an added entry "family_id" under livetableColumn and an updated license.

Big thanks to @sdumitriu for a clean solution.

### CODE REVIEW

**Comment by danielpgross** [comment]
Yes, this is a nice clean solution! Let's just fix up the indentation on the line below and then this is ready to go. 
https://github.com/Ruxuan/phenotips-niaid/blob/68853a238742b384d0f448e80a0d9e6c998c43fe/distribution/ui/src/main/resources/data/WebHome.xml#L258

**Comment by marta-** [comment]
Has  a`family_id` property been added to PatientClass in the Gene42 version of family studies? I don't see how this would work otherwise.

**Comment by Ruxuan** [comment]
The property has not yet been added. Currently the family id column still appears but data in the column is empty.

**Comment by marta-** [comment]
I see, so it doesn't work yet. But adding `family_id` to PatientClass isn't the right solution anyway. It would mean duplicating information from the FamilyReferenceClass, and it would be a pretty ugly hack.

I also disagree with adding a value to the configuration that is not supported by the administration UI. It will be lost as soon as somebody goes to that section of the administration and saves.

Long story short, this is not the right solution. The proper way to do it is:
- add support for selecting properties form classes other than PatientClass in `PhenoTips.DBConfigurationClassDisplayer` (ideally looking at the active form configuration like it's done in  `PhenoTips.ExportPreferences`
- add support for querying fields from other classes in data.AllData (probably using `<prop_name>/class` parameters like it's done in `PhenoTips/DatabaseFilters`.

**Comment by danielpgross** [comment]
Thanks @marta-, I had assumed that this was already reviewed/written by Sergiu and was already working on a basic level, so I didn't review in-depth. I am also partly in the dark here because I'm not familiar with the details of the implementation of FS. I should have confirmed this before being ready to merge. Thank you for doing a proper review and giving useful feedback.

@Ruxuan, it would have been good to have added a note here saying "this does not totally work yet" or something along those lines to make it clear for the reviewers.

Considering @marta-'s recommendation above, the implementation will need to be very different, so I'm closing this request.

**Comment by marta-** [comment]
I think the scope of Sergiu's input was the directory organization only. I'll create detailed tasks for the correct implementation.

**Comment by Ruxuan** [comment]
The task is currently here https://phenotips.atlassian.net/browse/NIAID-31
Thanks Marta!

**Pull request closed without merging**
