### PR TITLE
Implementation of backend for sequencing reports subsection

### PR DESCRIPTION
**Pull request by teyden**
Commits after `a1072ec` are different from branch `genetic-evaluation-section`.

### CODE REVIEW

**Comment by teyden** [comment]
Hm, why does it show _all_ the commits I made from the other open pull request for branch `genetic-evaluation-section`?

**Comment by sdumitriu** [comment]
Maybe because when you created the branch, instead of creating it from master, you created it from the other branch.

**Comment by teyden** [comment]
Ah, I see. That's correct, I created this branch from the `genetic-evaluation-section` branch.

**Comment by teyden** [comment]
Please review @danielpgross @sebialex. Thanks!

**Pull request closed without merging**
